### ISSUE TITLE
Is it necessary to use the cellTag mapped with other chromosome?

### ISSUE THREAD

**Issue by shangguandong1996** [morris-lab/BiddyetalWorkflow#4]
Hi
I found when the **parsing** the output of bam, you mentioned you also output the other gene info

> With the CellTag reads extracted we use a custom gawk script to parse the file and retain only the information we need. This scripts identifies and extracts the CellTag, Cell Barcode, and UMI sequences associated with each CellTag read. Furthermore, the read ID, read sequence, and **any genes the read aligned to are extracted as well**. This allows us to accurately quantify each CellTag and associate the CellTags with the correct cells. The output of this script is a tab delimited file with the following collumns: Read.ID, Read.Seq, Cell.BC, UMI, Cell.Tag, Gene. We will use this file to quantify and filter the CellTag data. Note that the regular expression identifying CellTagMEF has two bases added to the beginning. This is a "stricter" CellTag motif which helps filter out some erroneous CellTag reads.

But in my thinking, the only useful reads for celltag is in the **CellTag.UTR** or **GFP** chromosome and not other chromosome.
(Please correct me if I misunderstand something). 
So is it necessary to keep these reads from other chromosome for downstream analysising ?

Best wishes
Guandong Shang

**Comment by babiddy** [comment]
Hi Guandong,

Ideally, you are correct that we should only need reads that mapped to the CellTag.UTR or GFP chromosomes. But during our analysis, we found a number of CellTag reads that went unmapped. So in order to include CellTag reads that were unmapped we identified and extracted all of the CellTag reads from the BAM file. You can then filter out any reads that may have been mapped to chromosomes other than the CellTag.UTR or GFP chromosomes. But I would suggest including the unmapped CellTag reads in your analysis.

I hope this helps!

Best,
Brent

**Comment by shangguandong1996** [comment]
Thanks for your reply, Brent :)
And I have another question that why should cut the transgene into GFP and CellTag. If I use the entire sequence like below , will there be any side effects?
![图片](https://user-images.githubusercontent.com/22555126/90707098-67713e00-e2c9-11ea-8bf7-ec165966aff9.png)


Best
Guandong Shang

**Comment by shangguandong1996** [comment]
Get it, thanks again for your reply :).
